[Variables]

Wheel=1
Rad=200
RadXOffset=30
RadYOffset=30
IconSize=64

FontFace="Calvin and Hobbes Normal"
TitleFont="Calvin and Hobbes"

LargeFont=40
MedFont=15
SmallFont=10

BaseColor=255,255,255
RightColor=207, 247, 252
LeftColor=252, 210, 209
BackColor=#BaseColor#,60
WheelColor=#BaseColor#,100
TitleColor=#BaseColor#

@Include=#@#Universal/meters.inc

[TopMeter]
Y=5r

[TempMeter]
FontSize=#MedFont#