[Variables]

FontFace="Rockwell"
TitleFont="Rockwell"

LargeFont=40
MedFont=15
SmallFont=10

EyeColor=255, 174, 23
MouthColor=233, 117, 116
YellowColor=255,243,105
GreenColor=150,254,107

BaseColor=255,255,255
RightColor=#MouthColor#
LeftColor=#EyeColor#
BackColor=#BaseColor#,60
WheelColor=#BaseColor#,100
TitleColor=#BaseColor#

@Include=#@#Universal/meters.inc

[TopMeter]
Y=5r

[TempMeter]
FontSize=#MedFont#