[Variables]

FontFace="Rockwell"
TitleFont="Rockwell"

LargeFont=40
MedFont=15
SmallFont=10

RedColor=253,107,108
BlueColor=109,105,252
YellowColor=255,243,105
GreenColor=150,254,107

BaseColor=255,255,255
RightColor=#BlueColor#
LeftColor=#GreenColor#
BackColor=#BaseColor#,60
WheelColor=#BaseColor#,100
TitleColor=#BaseColor#

@Include=#@#Universal/meters.inc

[TopMeter]
Y=5r

[TempMeter]
FontSize=#MedFont#